/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.presentation;

import co.unicauca.restaurant.access.IProductRepository;
import co.unicauca.restaurant.access.ItalianRepositoriImplArrays;
import co.unicauca.restaurant.access.OrientalRepositoryImplArrays;
import co.unicauca.restaurant.domain.Dish;
import co.unicauca.restaurant.domain.Menu;
import co.unicauca.restaurant.domain.Product;
import co.unicauca.restaurant.domain.Size;
import co.unicauca.restaurant.orientalApp.ItalianDish;
import co.unicauca.restaurant.orientalApp.OrientalDish;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AgregarPC extends javax.swing.JInternalFrame {
    IProductRepository repo;
    private final List<Menu> menus;
    private Dish plat;
    private String ruta;
    /**
     * Creates new form AgregarPC
     * @param allMenus
     */
    public AgregarPC(List<Menu> allMenus) {
        initComponents();
        plat=new Dish();
        menus=allMenus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxBase = new javax.swing.JComboBox<>();
        txtNom = new java.awt.TextField();
        cbxAcom = new javax.swing.JComboBox<>();
        btnSelImagen = new javax.swing.JButton();
        txtAgregarPLato = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxTamanio = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Platos a la Carta");

        jLabel1.setText("Nombre:");

        jLabel3.setText("Base:");

        jLabel4.setText("Acompañantes:");

        jLabel5.setText("Imagen:");

        cbxBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------" }));

        cbxAcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------" }));

        btnSelImagen.setText("Seleccionar imagen");
        btnSelImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelImagenActionPerformed(evt);
            }
        });

        txtAgregarPLato.setText("Agregar Plato");
        txtAgregarPLato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarPLatoActionPerformed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Oriental", "Italiano" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo:");

        jLabel2.setText("Tamaño:");

        cbxTamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "PERSONAL", "DOBLE", "FAMILIAR" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAgregarPLato)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(cbxAcom, 0, 165, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxBase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTamanio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxBase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAgregarPLato)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelImagenActionPerformed
        JFileChooser jfc=new JFileChooser();
        int var=jfc.showOpenDialog(this);
        if (var==JFileChooser.APPROVE_OPTION) {
            ruta=jfc.getSelectedFile().getAbsolutePath();
        } 
    }//GEN-LAST:event_btnSelImagenActionPerformed

    private void txtAgregarPLatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarPLatoActionPerformed
        Menu menuOri=new Menu("Oriental");
        Menu menuIta=new Menu("Italiano");
        String base,acompa,nombre,tipo,tamanio;
        String [] bas; 
        String [] acom;
        try {
            nombre = txtNom.getText();
            tipo = cbxTipo.getSelectedItem().toString();
            tamanio = cbxTamanio.getSelectedItem().toString();
            base = cbxBase.getSelectedItem().toString();
            bas = base.split(",");
            acompa = cbxAcom.getSelectedItem().toString();
            acom = acompa.split(",");

            Product ba = new Product(Integer.parseInt(bas[0]), bas[1], Double.parseDouble(bas[2]));
            Product ac = new Product(Integer.parseInt(acom[0]), acom[1], Double.parseDouble(acom[2]));
            if (tipo.equals("Oriental")) {
                OrientalDish ori = new OrientalDish(nombre, ruta, 0d);
                ori.setBase(ba);
                ori.addOption(ac);
                ori.setSize(Size.valueOf(tamanio));
                plat = ori;
                menuOri.setPlatos(plat);
                menus.add(menuOri);
            } else if (tipo.equals("Italiano")) {
                ItalianDish ita = new ItalianDish(nombre, ruta, 0d);
                ita.setBase(ba);
                ita.addOption(ac);
                ita.setSize(Size.valueOf(tamanio));
                plat = ita;
                menuIta.setPlatos(plat);
                menus.add(menuIta);
            }
            JOptionPane.showMessageDialog(null, "Registro del plato exitoso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al ingresar", "Error", ERROR);
        }
        txtNom.setText("");
        cbxTipo.setSelectedIndex(0);
        cbxTamanio.setSelectedIndex(0);
        cbxBase.setSelectedIndex(0);
        cbxAcom.setSelectedIndex(0);
    }//GEN-LAST:event_txtAgregarPLatoActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        cbxBase.removeAllItems();
        cbxAcom.removeAllItems();
        if (cbxTipo.getSelectedItem().toString().equals("Oriental")) {
            repo = new OrientalRepositoryImplArrays();
            for (Product obj : repo.findAll()) {
                if (obj.getId() < 4) {
                    cbxBase.addItem(obj.getId() + "," + obj.getName() + "," + obj.getPrice());
                } else {
                    cbxAcom.addItem(obj.getId() + "," + obj.getName() + "," + obj.getPrice());
                }
            }
        }else if(cbxTipo.getSelectedItem().toString().equals("Italiano")){
            repo = new ItalianRepositoriImplArrays();
            for (Product obj : repo.findAll()) {
                if (obj.getId() < 4) {
                    cbxBase.addItem(obj.getId() + "," + obj.getName() + "," + obj.getPrice());
                } else {
                    cbxAcom.addItem(obj.getId() + "," + obj.getName() + "," + obj.getPrice());
                }
            }
        }
    }//GEN-LAST:event_cbxTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelImagen;
    private javax.swing.JComboBox<String> cbxAcom;
    private javax.swing.JComboBox<String> cbxBase;
    private javax.swing.JComboBox<String> cbxTamanio;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton txtAgregarPLato;
    private java.awt.TextField txtNom;
    // End of variables declaration//GEN-END:variables
}
