/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurant.presentation;

import co.unicauca.restaurant.access.IProductRepository;
import co.unicauca.restaurant.domain.Dish;
import co.unicauca.restaurant.domain.Menu;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class MostrarPC extends javax.swing.JInternalFrame {
    IProductRepository repo;
    List<Dish> platos;
    List<Menu> menus;
    /**
     * Creates new form MostrarPC
     * @param allMenus
     */
    public MostrarPC(List<Menu> allMenus) {
        initComponents();
        menus=allMenus;
        for (Menu men : menus) {
            platos=men.getPlatos();
            for (Dish pla : platos) {
                cbxPlato.addItem(men.getNombre()+","+pla.getNombre());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        cbxPlato = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Mostrar Platos a la Carta");

        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbxPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------" }));
        cbxPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        lblPrecio.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cbxPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(lblPrecio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(cbxPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPrecio))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlatoActionPerformed
        String menu=cbxPlato.getSelectedItem().toString();
        String [] me=menu.split(",");
        for (Menu men : menus) {
            if (men.getNombre().equals(me[0])) {
                for (Dish pla : men.getPlatos()) {
                    if (pla.getNombre().equalsIgnoreCase(me[1])) {
                        lblPrecio.setText(pla.getPrice() + "");
                        lblImagen.setIcon(new ImageIcon(pla.getImagen()));
                    }
                    
                }
            }
            
        }
        
        
        
    }//GEN-LAST:event_cbxPlatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPrecio;
    // End of variables declaration//GEN-END:variables
}
